# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 1


[[main]]
  name = "Experience"
  url = "#experience"
  weight = 2


[[main]]
  name = "Publications"
  url = "#publications"
  weight = 3


[[main]]
  name = "Research"
  url = "#research"
  weight = 4

[[main]]
  name = "Gallery"
  url = "#gallery"
  weight = 5

#[[main]]
#  name = "News"
#  url = "#posts"
#  weight = 5

[[main]]
  name = "CV"
  url = "files/zeynepersoy_cv.pdf"
  weight = 7
